const activitiesData = [
    { activityValue: "-1", activity: " לכל הקטגוריות" },
    { activityValue: "-1", activity: " קרוספיט ופונקציונלי" },
    { activityValue: "1379", activity: "Crossfit(R)" },
    { activityValue: "1378", activity: "Functional" },
    { activityValue: "1377", activity: " אימון פונקציונלי" },
    { activityValue: "1376", activity: " קרוספיט(R)" },
    { activityValue: "-1", activity: "----אטרקציות ספורטיביות-- -" },
    { activityValue: "1364", activity: "Tricking" },
    { activityValue: "1372", activity: "אומגה" },
    { activityValue: "1413", activity: "אופניים" },
    { activityValue: "1381", activity: " אטרקציות ספורטיביות" },
    { activityValue: "1384", activity: " אקרו - יוגה" },
    { activityValue: "1369", activity: "באולינג" },
    { activityValue: "1196", activity: "בננה" },
    { activityValue: "1320", activity: " בריכת כדורים" },
    { activityValue: "1183", activity: " החלקה על קרח " },
    { activityValue: "1187", activity: "טיול רינג'ר 3 איש" },
    { activityValue: "1188", activity: "טיול רינג'ר 4 איש" },
    { activityValue: "1283", activity: "טרמפולינה" },
    { activityValue: "1370", activity: " לייזר טאג " },
    { activityValue: "1386", activity: " מגלשות מים " },
    { activityValue: "1385", activity: " מיני גולף" },
    { activityValue: "1199", activity: " מצנח רחיפה" },
    { activityValue: "1278", activity: "מתקן נינג'ה" },
    { activityValue: "1198", activity: " ספורט ימי" },
    { activityValue: "1382", activity: " סקי מים" },
    { activityValue: "1373", activity: " פארק חבלים" },
    { activityValue: "1383", activity: " פארק מים" },
    { activityValue: "1334", activity: "פארקור" },
    { activityValue: "1346", activity: "פוצ'יוולי" },
    { activityValue: "1476", activity: " צלילה ושנורקלינג" },
    { activityValue: "1282", activity: " קיר טיפוס" },
    { activityValue: "-1", activity: "----ספורט ימי---" },
    { activityValue: "1470", activity: "Pilates Sup" },
    { activityValue: "1469", activity: "Yoga Sup" },
    { activityValue: "1393", activity: "בננות" },
    { activityValue: "1202", activity: " גלישת סאפ " },
    { activityValue: "1335", activity: " גלישת גלים" },
    { activityValue: "1203", activity: " גלישת רוח" },
    { activityValue: "1389", activity: " השכרת גלשן" },
    { activityValue: "1390", activity: " השכרת סאפ " },
    { activityValue: "1391", activity: " וייקבורד" },
    { activityValue: "1396", activity: " מגלשות מים" },
    { activityValue: "1394", activity: " מצנחי רחיפה " },
    { activityValue: "1392", activity: " מצנחים " },
    { activityValue: "1387", activity: " ספורט ימי" },
    { activityValue: "1336", activity: " סקי מים" },
    { activityValue: "1395", activity: " פארק מים" },
    { activityValue: "1475", activity: " צלילה ושנורקלינג" },
    { activityValue: "1205", activity: "קיאקים" },
    { activityValue: "1204", activity: " שייט מפרשיות וקטמרנים" },
    { activityValue: "1356", activity: " שיעורי גלישה" },
    { activityValue: "1388", activity: " שיעורי סאפ" },
    { activityValue: "-1", activity: "----ריקוד ---" },
    { activityValue: "1281", activity: " אירובי דאנס" },
    { activityValue: "1268", activity: " בלט קלאסי" },
    { activityValue: "1397", activity: "ג'אז" },
    { activityValue: "1269", activity: "ג'אז, ג'אז לירי/מודרני" },
    { activityValue: "1274", activity: " היפ הופ" },
    { activityValue: "1401", activity: "זומבה" },
    { activityValue: "1402", activity: " חישוק Hula Hoop" },
    { activityValue: "1321", activity: " טוורקינג Twerk" },
    { activityValue: "1400", activity: "מודרני" },
    { activityValue: "1399", activity: "מחול" },
    { activityValue: "1357", activity: "סלסה" },
    { activityValue: "1318", activity: "פלמנקו" },
    { activityValue: "1210", activity: " ריקוד על עמוד" },
    { activityValue: "1354", activity: " ריקודי בטן" },
    { activityValue: "1398", activity: " שיעורי ריקוד" },
    { activityValue: "-1", activity: "----אומנויות לחימה---" },
    { activityValue: "1226", activity: "FIGHT CAMP" },
    { activityValue: "1229", activity: " Kettlebell & Boxing" },
    { activityValue: "1225", activity: "MMA" },
    { activityValue: "1235", activity: " אגרוף קלאסי" },
    { activityValue: "1236", activity: " אגרוף תאילנדי" },
    { activityValue: "1403", activity: " אומניות לחימה" },
    { activityValue: "1212", activity: "ג'ודו" },
    { activityValue: "1238", activity: "ג'יוג'יטסו ברזליאי" },
    { activityValue: "1466", activity: "טאי צ'י" },
    { activityValue: "1332", activity: "טאקוונדו" },
    { activityValue: "1464", activity: "צ'י קונג" },
    { activityValue: "1366", activity: "קפוארה" },
    { activityValue: "1279", activity: "קראטה" },
    { activityValue: "1280", activity: " קרב מגע" },
    { activityValue: "-1", activity: "----קיר טיפוס---" },
    { activityValue: "1404", activity: "בולדרינג" },
    { activityValue: "1405", activity: " טיפוס עם רתמה" },
    { activityValue: "1292", activity: " קיר טיפוס" },
    { activityValue: "-1", activity: "----יוגה ופילאטיס---" },
    { activityValue: "1412", activity: "Mindfulness" },
    { activityValue: "1339", activity: "power yoga" },
    { activityValue: "1287", activity: " איינגר יוגה" },
    { activityValue: "1374", activity: " אקרו - יוגה" },
    { activityValue: "1331", activity: "אשטנגה" },
    { activityValue: "1323", activity: "ביקראם" },
    { activityValue: "1420", activity: "ג'יירוטוניק" },
    { activityValue: "1329", activity: "האטה" },
    { activityValue: "1363", activity: "ויג'נאנאה" },
    { activityValue: "1312", activity: "ויוגה ג'וי" },
    { activityValue: "1330", activity: "ויניאסה" },
    { activityValue: "1360", activity: "טאי צ'י" },
    { activityValue: "1301", activity: "יוגה" },
    { activityValue: "1341", activity: " יוגה אווירית" },
    { activityValue: "1313", activity: "יוגה ג'וי" },
    { activityValue: "1421", activity: " יוגה חמה" },
    { activityValue: "1324", activity: " יוגה טיפולית" },
    { activityValue: "1410", activity: " יוגה ערסלים" },
    { activityValue: "1358", activity: "מדיטציה" },
    { activityValue: "1411", activity: " עמידת ידיים" },
    { activityValue: "1406", activity: "פילאטיס" },
    { activityValue: "1407", activity: " פילאטיס מזרן" },
    { activityValue: "1408", activity: " פילאטיס מכשירים" },
    { activityValue: "1314", activity: "צ'י יוגה" },
    { activityValue: "1342", activity: "קונדליני" },
    { activityValue: "-1", activity: "----משחקי כדור---" },
    { activityValue: "1451", activity: "באולינג" },
    { activityValue: "1449", activity: "בדמינגטון" },
    { activityValue: "1447", activity: " השכרת מגרש טניס" },
    { activityValue: "1445", activity: "טניס" },
    { activityValue: "1472", activity: " טניס שולחן" },
    { activityValue: "1450", activity: " כדורעף חופים" },
    { activityValue: "1448", activity: "סקווש" },
    { activityValue: "1452", activity: "פוצ'יוולי" },
    { activityValue: "1446", activity: " שיעור טניס" },
    { activityValue: "-1", activity: "----הריון / אמהות--" },
    { activityValue: "1459", activity: " אימון לנשים אחרי הריון" },
    { activityValue: "1458", activity: " אימון לנשים בהריון" },
    { activityValue: "1460", activity: " אימון עם בייביסיטר" },
    { activityValue: "1461", activity: " אימון עם תינוקות" },
    { activityValue: "1463", activity: " יוגה הריון" },
    { activityValue: "1462", activity: " פילאטיס הריון" },
    { activityValue: "-1", activity: "----ONLINE ---" },
    { activityValue: "1468", activity: " שיעורי אונליין" },
    { activityValue: "-1", activity: "--- נינג'ה---" },
    { activityValue: "-1", activity: "----אטרקציות ספורטיביות---" },
    { activityValue: "1477", activity: "נינג'ה" },
    { activityValue: "-1", activity: "----מועדון כושר---" },
    { activityValue: "1474", activity: "Open Gym" },
    { activityValue: "1414", activity: " חדר כושר לגברים בלבד" },
    { activityValue: "1415", activity: " חדר כושר לנשים בלבד" },
    { activityValue: "1416", activity: " חדר כושר מופרד" },
    { activityValue: "92", activity: " חדר כושר " },
    { activityValue: "53", activity: " אימון ילדים / נוער" },
    { activityValue: "-1", activity: "----שיעורי סטודיו---" },
    { activityValue: "1315", activity: "ג'יירוקינסיס" },
    { activityValue: "1294", activity: "Barre" },
    { activityValue: "98", activity: "BODY PUMP" },
    { activityValue: "1417", activity: "Bootcamp" },
    { activityValue: "100", activity: "Core" },
    { activityValue: "1418", activity: "Crossfit(R)" },
    { activityValue: "1174", activity: "Functional training" },
    { activityValue: "1176", activity: "HIIT Training" },
    { activityValue: "1288", activity: "Kangoo Jumps" },
    { activityValue: "108", activity: "Les Mills" },
    { activityValue: "1431", activity: "Mindfulness" },
    { activityValue: "1467", activity: "Power" },
    { activityValue: "1419", activity: "Prama" },
    { activityValue: "1221", activity: "TABATA" },
    { activityValue: "1365", activity: "Tricking" },
    { activityValue: "1179", activity: "TRX" },
    { activityValue: "1428", activity: "Twerk טווארקינג" },
    { activityValue: "90", activity: " אומנויות לחימה" },
    { activityValue: "119", activity: "אוסטיופורוזיס" },
    { activityValue: "1305", activity: " אחרי לידה" },
    { activityValue: "1425", activity: " אימון לנשים בהריון" },
    { activityValue: "141", activity: " אימון מחזורי" },
    { activityValue: "1424", activity: " אימון פונקציונלי" },
    { activityValue: "1211", activity: "אירובי" },
    { activityValue: "1309", activity: " אקרובטיקה אווירית" },
    { activityValue: "1426", activity: " אקרו - יוגה " },
    { activityValue: "63", activity: " בניית עצם" },
    { activityValue: "1316", activity: "ג'יירוטניק" },
    { activityValue: "1362", activity: "גמישות" },
    { activityValue: "1173", activity: "גרביטי" },
    { activityValue: "1422", activity: " היפ הופ" },
    { activityValue: "1423", activity: "זומבה" },
    { activityValue: "1429", activity: " חישוק Hula Hoop" },
    { activityValue: "1371", activity: " טרמפו - פיט" },
    { activityValue: "58", activity: "יוגה" },
    { activityValue: "1432", activity: "מדיטציה" },
    { activityValue: "96", activity: "מדרגה" },
    { activityValue: "1473", activity: "מובמנט" },
    { activityValue: "138", activity: "מתיחות" },
    { activityValue: "1201", activity: "סטודיו" },
    { activityValue: "66", activity: "ספינינג" },
    { activityValue: "97", activity: " עיצוב וחיטוב / עיצוב דינאמי" },
    { activityValue: "1427", activity: " עמידת ידיים" },
    { activityValue: "55", activity: "פילאטיס" },
    { activityValue: "56", activity: " פילאטיס מכשירים" },
    { activityValue: "1180", activity: "פלדנקרייז" },
    { activityValue: "1367", activity: "קטלבלס" },
    { activityValue: "57", activity: "קיקבוקס" },
    { activityValue: "59", activity: "ריקוד" },
    { activityValue: "1430", activity: " ריקוד על עמוד" },
    { activityValue: "1304", activity: " שיעורי אימהות ותינוקות" },
    { activityValue: "-1", activity: "----בריכה ---" },
    { activityValue: "130", activity: "בריכה" },
    { activityValue: "1433", activity: " בריכה אולימפית" },
    { activityValue: "70", activity: " בריכה מחוממת " },
    { activityValue: "121", activity: " בריכה סגורה" },
    { activityValue: "1435", activity: " בריכת מלון" },
    { activityValue: "1178", activity: " בריכת פעוטות" },
    { activityValue: "1177", activity: " בריכת קיץ" },
    { activityValue: "1436", activity: " פארק מים" },
    { activityValue: "1434", activity: " קאנטרי קלאב" },
    { activityValue: "1351", activity: " שחיה לילית" },
    { activityValue: "71", activity: " שעורי שחיה " },
    { activityValue: "-1", activity: "----Outdoor ---" },
    { activityValue: "1441", activity: "Bootcamp" },
    { activityValue: "1355", activity: "street workout" },
    { activityValue: "1438", activity: "TRX" },
    { activityValue: "1465", activity: " אומניות לחימה " },
    { activityValue: "74", activity: " אימון חוץ" },
    { activityValue: "1439", activity: " אימון מחזורי" },
    { activityValue: "1256", activity: " אימון פונקציונלי" },
    { activityValue: "1265", activity: "אימוני ריצה" },
    { activityValue: "1266", activity: " אימוני רכיבה " },
    { activityValue: "1440", activity: "אקרו-יוגה" },
    { activityValue: "115", activity: "גלישה" },
    { activityValue: "79", activity: "טניס" },
    { activityValue: "1444", activity: "טרמפולינות" },
    { activityValue: "1302", activity: "יוגה" },
    { activityValue: "1291", activity: " כדורעף חופים" },
    { activityValue: "1437", activity: "סאפ" },
    { activityValue: "77", activity: " ספורט ימי" },
    { activityValue: "1442", activity: " סקי מים" },
    { activityValue: "1443", activity: " פארק חבלים" },
    { activityValue: "1333", activity: "פארקור" },
    { activityValue: "1344", activity: "פוצ'יוולי" },
    { activityValue: "1375", activity: "פילאטיס" },
    { activityValue: "103", activity: " קבוצת אופניים " },
    { activityValue: "1349", activity: " קבוצת טריאתלון" },
    { activityValue: "76", activity: " קבוצת מרתון" },
    { activityValue: "75", activity: " קבוצת ריצה" },
    { activityValue: "125", activity: "קיר טיפוס" },
    { activityValue: "1471", activity: "ריקוד" },
    { activityValue: "-1", activity: "----תוספות משלימות---" },
    { activityValue: "1350", activity: "EMS" },
    { activityValue: "85", activity: "ג'קוזי" },
    { activityValue: "1409", activity: " חוף ים פרטי" },
    { activityValue: "1454", activity: "חניה" },
    { activityValue: "1456", activity: "מגבות" },
    { activityValue: "111", activity: " מלתחות אישיות" },
    { activityValue: "1455", activity: "מקלחות" },
    { activityValue: "1457", activity: " מתחם מתנפחים" },
    { activityValue: "84", activity: "סאונה" },
    { activityValue: "1326", activity: "ספא" },
    { activityValue: "127", activity: "עיסויים" },
    { activityValue: "82", activity: "קפיטריה" }
]

export default activitiesData;