
const data = [
    { value: "-1", data: "- לכל הערים -  " },
    { value: "57", data: "אבן יהודה" },
    { value: "3170", data: "אודים" },
    { value: "90", data: "אופקים" },
    { value: "55", data: "אור יהודה" },
    { value: "2097", data: "אור עקיבא" },
    { value: "1095", data: "אורנית" },
    { value: "66", data: "אזור" },
    { value: "30", data: "אילת" },
    { value: "3178", data: "אלון שבות" },
    { value: "47", data: "אלעד" },
    { value: "3167", data: "אלפי מנשה" },
    { value: "3209", data: "אפיק" },
    { value: "58", data: "אפרת" },
    { value: "1094", data: "אריאל" },
    { value: "3206", data: "ארסוף" },
    { value: "12", data: "אשדוד" },
    { value: "9", data: "אשקלון" },
    { value: "2142", data: "באר יעקב" },
    { value: "8", data: "באר שבע" },
    { value: "2103", data: "בארות יצחק" },
    { value: "3193", data: "בארותיים" },
    { value: "2155", data: "בורגתא" },
    { value: "29", data: "בית אריה" },
    { value: "2121", data: "בית דגן" },
    { value: "3197", data: "בית הלל" },
    { value: "3202", data: "בית חשמונאי" },
    { value: "2151", data: "בית יהושוע" },
    { value: "3158", data: "בית ינאי" },
    { value: "3188", data: "בית שאן" },
    { value: "59", data: "בית שמש" },
    { value: "42", data: "בני ברק" },
    { value: "3181", data: "בני דרום" },
    { value: "2106", data: "בני עטרות" },
    { value: "49", data: "בנימינה" },
    { value: "3156", data: "בר אילן" },
    { value: "3162", data: "בת חפר" },
    { value: "17", data: "בת ים" },
    { value: "3218", data: "גבעת זאב" },
    { value: "3182", data: "גבעת כוח" },
    { value: "2108", data: "גבעת שמואל" },
    { value: "4", data: "גבעתיים" },
    { value: "80", data: "גדרה" },
    { value: "2123", data: "גוש עציון" },
    { value: "63", data: "גליל ים" },
    { value: "3165", data: "גן חיים" },
    { value: "65", data: "גן יבנה" },
    { value: "85", data: "גני תקווה" },
    { value: "3180", data: "דגניה א" },
    { value: "2124", data: "דולב" },
    { value: "44", data: "דימונה" },
    { value: "7", data: "הוד השרון" },
    { value: "21", data: "הרצליה" },
    { value: "32", data: "וינגייט" },
    { value: "48", data: "זכרון יעקב" },
    { value: "27", data: "חדרה" },
    { value: "23", data: "חולון" },
    { value: "2148", data: "חוף הכרמל" },
    { value: "70", data: "חופית שבי ציון" },
    { value: "3220", data: "חיננית" },
    { value: "39", data: "חיפה" },
    { value: "3157", data: "חפץ חיים" },
    { value: "1096", data: "חצור הגלילית" },
    { value: "3161", data: "חריש" },
    { value: "3215", data: "חשמונאים" },
    { value: "2153", data: "טבריה" },
    { value: "3214", data: "טייבה" },
    { value: "82", data: "טירת הכרמל" },
    { value: "3222", data: "טמרה" },
    { value: "20", data: "יבנה" },
    { value: "14", data: "יהוד" },
    { value: "56", data: "יוקנעם" },
    { value: "3189", data: "ים המלח" },
    { value: "3160", data: "ינוב" },
    { value: "76", data: "יסוד המעלה" },
    { value: "71", data: "יסעור" },
    { value: "3191", data: "יפו" },
    { value: "3", data: "ירושלים" },
    { value: "3205", data: "ישראל" },
    { value: "2127", data: "כוכב יאיר" },
    { value: "2156", data: "כנות" },
    { value: "2096", data: "כפר גלעדי" },
    { value: "81", data: "כפר ורדים" },
    { value: "2150", data: "כפר חורפיש" },
    { value: "3173", data: "כפר טרומן" },
    { value: "50", data: "כפר יונה" },
    { value: "24", data: "כפר סבא" },
    { value: "3194", data: "כפר סירקין" },
    { value: "3211", data: "כפר שמריהו" },
    { value: "3172", data: "כרמי יוסף" },
    { value: "83", data: "כרמיאל" },
    { value: "2144", data: "לוד" },
    { value: "28", data: "לוד / רמלה" },
    { value: "2129", data: "לפיד" },
    { value: "22", data: "מבשרת ציון" },
    { value: "6", data: "מודיעין" },
    { value: "2118", data: "מושב גאולים" },
    { value: "3201", data: "מושב חגור" },
    { value: "3203", data: "מושב מזור" },
    { value: "2119", data: "מושב שורש" },
    { value: "2098", data: "מזכרת בתיה" },
    { value: "3164", data: "מטולה" },
    { value: "3169", data: "מכבים" },
    { value: "2099", data: "מסילת ציון" },
    { value: "2101", data: "מסעדה" },
    { value: "2122", data: "מעיין צבי" },
    { value: "3198", data: "מעיליא" },
    { value: "60", data: "מעלה אדומים" },
    { value: "52", data: "מעלות" },
    { value: "2102", data: "מרום גולן" },
    { value: "54", data: "מרום הגליל" },
    { value: "84", data: "משגב" },
    { value: "3174", data: "משמרת" },
    { value: "53", data: "נהריה" },
    { value: "3176", data: "נוב" },
    { value: "3217", data: "נוף הגליל" },
    { value: "3177", data: "נופית חרמון" },
    { value: "2128", data: "ניו יורק" },
    { value: "3175", data: "ניר דוד" },
    { value: "74", data: "נס עמים" },
    { value: "18", data: "נס ציונה" },
    { value: "3159", data: "נעורים" },
    { value: "2149", data: "נצרת עילית" },
    { value: "61", data: "נשר" },
    { value: "91", data: "נתיבות" },
    { value: "34", data: "נתניה" },
    { value: "2105", data: "סביון" },
    { value: "3199", data: "סח'נין" },
    { value: "2116", data: "עין ורד" },
    { value: "3210", data: "עכו" },
    { value: "46", data: "עפולה" },
    { value: "2147", data: "עתלית" },
    { value: "26", data: "פרדס חנה" },
    { value: "3166", data: "פרדסיה" },
    { value: "10", data: "פתח תקווה" },
    { value: "2100", data: "צור הדסה" },
    { value: "75", data: "צפת" },
    { value: "93", data: "קדימה צורן" },
    { value: "3213", data: "קיבוץ אלונים" },
    { value: "3163", data: "קיבוץ גבת" },
    { value: "67", data: "קיבוץ גשר הזיו" },
    { value: "3208", data: "קיבוץ דן" },
    { value: "3216", data: "קיבוץ דפנה" },
    { value: "88", data: "קיבוץ הגושרים" },
    { value: "3200", data: "קיבוץ מעוז חיים" },
    { value: "2112", data: "קיבוץ מעיין צבי" },
    { value: "3192", data: "קיבוץ מרחביה" },
    { value: "68", data: "קיבוץ סער" },
    { value: "31", data: "קיבוץ עוגן" },
    { value: "2117", data: "קיבוץ עינת" },
    { value: "3186", data: "קיבוץ רשפים" },
    { value: "3187", data: "קיבוץ תל יוסף" },
    { value: "19", data: "קיסריה" },
    { value: "3219", data: "קריות" },
    { value: "64", data: "קריית אתא" },
    { value: "79", data: "קריית גת" },
    { value: "15", data: "קרית אונו" },
    { value: "2143", data: "קרית אתא" },
    { value: "41", data: "קרית חיים" },
    { value: "3179", data: "קרית טבעון" },
    { value: "94", data: "קרית ים" },
    { value: "5", data: "קרית מוצקין" },
    { value: "38", data: "קרית מלאכי" },
    { value: "2152", data: "קרית ענבים" },
    { value: "87", data: "קרית שמונה" },
    { value: "2154", data: "קרני שומרון" },
    { value: "43", data: "ראש העין" },
    { value: "1097", data: "ראש פינה" },
    { value: "2", data: "ראשון לציון" },
    { value: "11", data: "רחובות" },
    { value: "2125", data: "רימונים" },
    { value: "3223", data: "רכסים" },
    { value: "2145", data: "רמלה" },
    { value: "2107", data: "רמת אפעל" },
    { value: "13", data: "רמת גן" },
    { value: "36", data: "רמת השרון" },
    { value: "51", data: "רמת ישי" },
    { value: "3168", data: "רעות" },
    { value: "33", data: "רעננה" },
    { value: "3204", data: "רשפון" },
    { value: "3185", data: "רשפים" },
    { value: "3207", data: "שאר ישוב" },
    { value: "89", data: "שדרות" },
    { value: "40", data: "שוהם" },
    { value: "2109", data: "שערי תקווה" },
    { value: "1", data: "תל אביב" },
    { value: "2104", data: "תל מונד" },
    { value: "2113", data: "תלמי אליעזר" },
    { value: "2114", data: "תלמי יפה" },
    { value: "3195", data: "תקוע" },
    { value: "-1", data: " לכל הקטגוריות " },
    { value: "-1", data: " קרוספיט ופונקציונלי" },
    { value: "1379", data: "Crossfit(R)" },
    { value: "1378", data: "Functional" },
    { value: "1377", data: " אימון פונקציונלי" },
    { value: "1376", data: " קרוספיט(R)" },
    { value: "-1", data: "----אטרקציות ספורטיביות-- -" },
    { value: "1364", data: "Tricking" },
    { value: "1372", data: "אומגה" },
    { value: "1413", data: "אופניים" },
    { value: "1381", data: " אטרקציות ספורטיביות" },
    { value: "1384", data: " אקרו - יוגה" },
    { value: "1369", data: "באולינג" },
    { value: "1196", data: "בננה" },
    { value: "1320", data: " בריכת כדורים" },
    { value: "1183", data: " החלקה על קרח " },
    { value: "1187", data: "טיול רינג'ר 3 איש" },
    { value: "1188", data: "טיול רינג'ר 4 איש" },
    { value: "1283", data: "טרמפולינה" },
    { value: "1370", data: " לייזר טאג " },
    { value: "1386", data: " מגלשות מים " },
    { value: "1385", data: " מיני גולף" },
    { value: "1199", data: " מצנח רחיפה" },
    { value: "1278", data: "מתקן נינג'ה" },
    { value: "1198", data: " ספורט ימי" },
    { value: "1382", data: " סקי מים" },
    { value: "1373", data: " פארק חבלים" },
    { value: "1383", data: " פארק מים" },
    { value: "1334", data: "פארקור" },
    { value: "1346", data: "פוצ'יוולי" },
    { value: "1476", data: " צלילה ושנורקלינג" },
    { value: "1282", data: " קיר טיפוס" },
    { value: "-1", data: "----ספורט ימי---" },
    { value: "1470", data: "Pilates Sup" },
    { value: "1469", data: "Yoga Sup" },
    { value: "1393", data: "בננות" },
    { value: "1202", data: " גלישת סאפ " },
    { value: "1335", data: " גלישת גלים" },
    { value: "1203", data: " גלישת רוח" },
    { value: "1389", data: " השכרת גלשן" },
    { value: "1390", data: " השכרת סאפ " },
    { value: "1391", data: " וייקבורד" },
    { value: "1396", data: " מגלשות מים" },
    { value: "1394", data: " מצנחי רחיפה " },
    { value: "1392", data: " מצנחים " },
    { value: "1387", data: " ספורט ימי" },
    { value: "1336", data: " סקי מים" },
    { value: "1395", data: " פארק מים" },
    { value: "1475", data: " צלילה ושנורקלינג" },
    { value: "1205", data: "קיאקים" },
    { value: "1204", data: " שייט מפרשיות וקטמרנים" },
    { value: "1356", data: " שיעורי גלישה" },
    { value: "1388", data: " שיעורי סאפ" },
    { value: "-1", data: "----ריקוד ---" },
    { value: "1281", data: " אירובי דאנס" },
    { value: "1268", data: " בלט קלאסי" },
    { value: "1397", data: "ג'אז" },
    { value: "1269", data: "ג'אז, ג'אז לירי/מודרני" },
    { value: "1274", data: " היפ הופ" },
    { value: "1401", data: "זומבה" },
    { value: "1402", data: " חישוק Hula Hoop" },
    { value: "1321", data: " טוורקינג Twerk" },
    { value: "1400", data: "מודרני" },
    { value: "1399", data: "מחול" },
    { value: "1357", data: "סלסה" },
    { value: "1318", data: "פלמנקו" },
    { value: "1210", data: " ריקוד על עמוד" },
    { value: "1354", data: " ריקודי בטן" },
    { value: "1398", data: " שיעורי ריקוד" },
    { value: "-1", data: "----אומנויות לחימה---" },
    { value: "1226", data: "FIGHT CAMP" },
    { value: "1229", data: " Kettlebell & Boxing" },
    { value: "1225", data: "MMA" },
    { value: "1235", data: " אגרוף קלאסי" },
    { value: "1236", data: " אגרוף תאילנדי" },
    { value: "1403", data: " אומניות לחימה" },
    { value: "1212", data: "ג'ודו" },
    { value: "1238", data: "ג'יוג'יטסו ברזליאי" },
    { value: "1466", data: "טאי צ'י" },
    { value: "1332", data: "טאקוונדו" },
    { value: "1464", data: "צ'י קונג" },
    { value: "1366", data: "קפוארה" },
    { value: "1279", data: "קראטה" },
    { value: "1280", data: " קרב מגע" },
    { value: "-1", data: "----קיר טיפוס---" },
    { value: "1404", data: "בולדרינג" },
    { value: "1405", data: " טיפוס עם רתמה" },
    { value: "1292", data: " קיר טיפוס" },
    { value: "-1", data: "----יוגה ופילאטיס---" },
    { value: "1412", data: "Mindfulness" },
    { value: "1339", data: "power yoga" },
    { value: "1287", data: " איינגר יוגה" },
    { value: "1374", data: " אקרו - יוגה" },
    { value: "1331", data: "אשטנגה" },
    { value: "1323", data: "ביקראם" },
    { value: "1420", data: "ג'יירוטוניק" },
    { value: "1329", data: "האטה" },
    { value: "1363", data: "ויג'נאנאה" },
    { value: "1312", data: "ויוגה ג'וי" },
    { value: "1330", data: "ויניאסה" },
    { value: "1360", data: "טאי צ'י" },
    { value: "1301", data: "יוגה" },
    { value: "1341", data: " יוגה אווירית" },
    { value: "1313", data: "יוגה ג'וי" },
    { value: "1421", data: " יוגה חמה" },
    { value: "1324", data: " יוגה טיפולית" },
    { value: "1410", data: " יוגה ערסלים" },
    { value: "1358", data: "מדיטציה" },
    { value: "1411", data: " עמידת ידיים" },
    { value: "1406", data: "פילאטיס" },
    { value: "1407", data: " פילאטיס מזרן" },
    { value: "1408", data: " פילאטיס מכשירים" },
    { value: "1314", data: "צ'י יוגה" },
    { value: "1342", data: "קונדליני" },
    { value: "-1", data: "----משחקי כדור---" },
    { value: "1451", data: "באולינג" },
    { value: "1449", data: "בדמינגטון" },
    { value: "1447", data: " השכרת מגרש טניס" },
    { value: "1445", data: "טניס" },
    { value: "1472", data: " טניס שולחן" },
    { value: "1450", data: " כדורעף חופים" },
    { value: "1448", data: "סקווש" },
    { value: "1452", data: "פוצ'יוולי" },
    { value: "1446", data: " שיעור טניס" },
    { value: "-1", data: "----הריון / אמהות--" },
    { value: "1459", data: " אימון לנשים אחרי הריון" },
    { value: "1458", data: " אימון לנשים בהריון" },
    { value: "1460", data: " אימון עם בייביסיטר" },
    { value: "1461", data: " אימון עם תינוקות" },
    { value: "1463", data: " יוגה הריון" },
    { value: "1462", data: " פילאטיס הריון" },
    { value: "-1", data: "----ONLINE ---" },
    { value: "1468", data: " שיעורי אונליין" },
    { value: "-1", data: "--- נינג'ה---" },
    { value: "-1", data: "----אטרקציות ספורטיביות---" },
    { value: "1477", data: "נינג'ה" },
    { value: "-1", data: "----מועדון כושר---" },
    { value: "1474", data: "Open Gym" },
    { value: "1414", data: " חדר כושר לגברים בלבד" },
    { value: "1415", data: " חדר כושר לנשים בלבד" },
    { value: "1416", data: " חדר כושר מופרד" },
    { value: "92", data: " חדר כושר " },
    { value: "53", data: " אימון ילדים / נוער" },
    { value: "-1", data: "----שיעורי סטודיו---" },
    { value: "1315", data: "ג'יירוקינסיס" },
    { value: "1294", data: "Barre" },
    { value: "98", data: "BODY PUMP" },
    { value: "1417", data: "Bootcamp" },
    { value: "100", data: "Core" },
    { value: "1418", data: "Crossfit(R)" },
    { value: "1174", data: "Functional training" },
    { value: "1176", data: "HIIT Training" },
    { value: "1288", data: "Kangoo Jumps" },
    { value: "108", data: "Les Mills" },
    { value: "1431", data: "Mindfulness" },
    { value: "1467", data: "Power" },
    { value: "1419", data: "Prama" },
    { value: "1221", data: "TABATA" },
    { value: "1365", data: "Tricking" },
    { value: "1179", data: "TRX" },
    { value: "1428", data: "Twerk טווארקינג" },
    { value: "90", data: " אומנויות לחימה" },
    { value: "119", data: "אוסטיופורוזיס" },
    { value: "1305", data: " אחרי לידה" },
    { value: "1425", data: " אימון לנשים בהריון" },
    { value: "141", data: " אימון מחזורי" },
    { value: "1424", data: " אימון פונקציונלי" },
    { value: "1211", data: "אירובי" },
    { value: "1309", data: " אקרובטיקה אווירית" },
    { value: "1426", data: " אקרו - יוגה " },
    { value: "63", data: " בניית עצם" },
    { value: "1316", data: "ג'יירוטניק" },
    { value: "1362", data: "גמישות" },
    { value: "1173", data: "גרביטי" },
    { value: "1422", data: " היפ הופ" },
    { value: "1423", data: "זומבה" },
    { value: "1429", data: " חישוק Hula Hoop" },
    { value: "1371", data: " טרמפו - פיט" },
    { value: "58", data: "יוגה" },
    { value: "1432", data: "מדיטציה" },
    { value: "96", data: "מדרגה" },
    { value: "1473", data: "מובמנט" },
    { value: "138", data: "מתיחות" },
    { value: "1201", data: "סטודיו" },
    { value: "66", data: "ספינינג" },
    { value: "97", data: " עיצוב וחיטוב / עיצוב דינאמי" },
    { value: "1427", data: " עמידת ידיים" },
    { value: "55", data: "פילאטיס" },
    { value: "56", data: " פילאטיס מכשירים" },
    { value: "1180", data: "פלדנקרייז" },
    { value: "1367", data: "קטלבלס" },
    { value: "57", data: "קיקבוקס" },
    { value: "59", data: "ריקוד" },
    { value: "1430", data: " ריקוד על עמוד" },
    { value: "1304", data: " שיעורי אימהות ותינוקות" },
    { value: "-1", data: "----בריכה ---" },
    { value: "130", data: "בריכה" },
    { value: "1433", data: " בריכה אולימפית" },
    { value: "70", data: " בריכה מחוממת " },
    { value: "121", data: " בריכה סגורה" },
    { value: "1435", data: " בריכת מלון" },
    { value: "1178", data: " בריכת פעוטות" },
    { value: "1177", data: " בריכת קיץ" },
    { value: "1436", data: " פארק מים" },
    { value: "1434", data: " קאנטרי קלאב" },
    { value: "1351", data: " שחיה לילית" },
    { value: "71", data: " שעורי שחיה " },
    { value: "-1", data: "----Outdoor ---" },
    { value: "1441", data: "Bootcamp" },
    { value: "1355", data: "street workout" },
    { value: "1438", data: "TRX" },
    { value: "1465", data: " אומניות לחימה " },
    { value: "74", data: " אימון חוץ" },
    { value: "1439", data: " אימון מחזורי" },
    { value: "1256", data: " אימון פונקציונלי" },
    { value: "1265", data: "אימוני ריצה" },
    { value: "1266", data: " אימוני רכיבה " },
    { value: "1440", data: "אקרו-יוגה" },
    { value: "115", data: "גלישה" },
    { value: "79", data: "טניס" },
    { value: "1444", data: "טרמפולינות" },
    { value: "1302", data: "יוגה" },
    { value: "1291", data: " כדורעף חופים" },
    { value: "1437", data: "סאפ" },
    { value: "77", data: " ספורט ימי" },
    { value: "1442", data: " סקי מים" },
    { value: "1443", data: " פארק חבלים" },
    { value: "1333", data: "פארקור" },
    { value: "1344", data: "פוצ'יוולי" },
    { value: "1375", data: "פילאטיס" },
    { value: "103", data: " קבוצת אופניים " },
    { value: "1349", data: " קבוצת טריאתלון" },
    { value: "76", data: " קבוצת מרתון" },
    { value: "75", data: " קבוצת ריצה" },
    { value: "125", data: "קיר טיפוס" },
    { value: "1471", data: "ריקוד" },
    { value: "-1", data: "----תוספות משלימות---" },
    { value: "1350", data: "EMS" },
    { value: "85", data: "ג'קוזי" },
    { value: "1409", data: " חוף ים פרטי" },
    { value: "1454", data: "חניה" },
    { value: "1456", data: "מגבות" },
    { value: "111", data: " מלתחות אישיות" },
    { value: "1455", data: "מקלחות" },
    { value: "1457", data: " מתחם מתנפחים" },
    { value: "84", data: "סאונה" },
    { value: "1326", data: "ספא" },
    { value: "127", data: "עיסויים" },
    { value: "82", data: "קפיטריה" }
]

export default data;